name: Aptos Test

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  # cancel redundant builds on PRs (only on PR, not on branches)
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  aptos_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup_aptos_cli
        with:
          version: 4.0.0
      - name: test_contract
        run: (cd libs && aptos move test --coverage --dev --skip-fetch-latest-git-deps --skip-attribute-checks) & (cd verifier && aptos move test --coverage --dev --skip-fetch-latest-git-deps --skip-attribute-checks) & (cd cpu && aptos move test --coverage --dev --skip-fetch-latest-git-deps --skip-attribute-checks) & (cd cpu-constraint-poly && aptos move test --coverage --dev --skip-fetch-latest-git-deps --skip-attribute-checks)